/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prog2exer3;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileOutputStream;
import java.lang.reflect.Array;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.Period;
import javax.swing.table.DefaultTableModel;
import java.util.Arrays; 
import java.util.List;
import java.util.ArrayList;
/**
 *
 * @author priscillalicup
 */
public class Customer extends javax.swing.JFrame {
int id=0;
int a = 0;
String [][] cust = new String [10][10];
int []num = new int[10];
String [][][] ord = new String [10][10][10];

private void showorders() {
    int y = Integer.parseInt(cid.getText());
    
    DefaultTableModel tblo = (DefaultTableModel) jTable3.getModel();
    tblo.setRowCount (0);
    
    for (int x=0; x<7; x++) {
        if(ord[y][x][0]!=null) {
            tblo.addRow (ord[y][x]);
        }
    }
            
}

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        cemail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        cbday = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cgen = new javax.swing.JComboBox<String>();
        cname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nlabel = new javax.swing.JLabel();
        cad = new javax.swing.JTextField();
        elabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        blabel = new javax.swing.JLabel();
        ccon = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        AddOrd = new javax.swing.JButton();
        Invoice = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cemailKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Customer ID");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Customer Bday");

        cbday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdayActionPerformed(evt);
            }
        });
        cbday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbdayKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Customer Recording System");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Customer Gender");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Customer Name");

        cgen.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cgen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        cname.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Customer Address");

        nlabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        nlabel.setText("Lastname, Firstname");

        elabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        elabel.setText("[a-z]@[a-z].com");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Customer Contact #");

        blabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        blabel.setText("mm/dd/yyyy");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Customer Email");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Contact", "Email", "Bday", "Gender"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice No.", "Pid", "PType", "PDesc", "Quantity", "Unit Price", "Date"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        AddOrd.setText("Add Order");
        AddOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddOrdActionPerformed(evt);
            }
        });

        Invoice.setText("Final Invoice");
        Invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvoiceActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Products");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Orders");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nlabel))
                            .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ccon, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(cemail)
                            .addComponent(cad))
                        .addGap(18, 18, 18)
                        .addComponent(elabel))
                    .addComponent(jLabel8)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cgen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbday)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddOrd)
                                    .addComponent(blabel)
                                    .addComponent(Invoice))
                                .addGap(23, 23, 23)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nlabel)
                            .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ccon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(elabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cgen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Invoice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddOrd)
                        .addGap(99, 99, 99))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cemailKeyReleased
        Boolean at=false;
        Boolean dotcom=false;
        for (int x=1; x<=cemail.getText().length();x++) {
            if (cemail.getText().substring(x-1,x).equals("@") && x>3) {
                at=true;
            } else {
                elabel.setForeground(Color.red);
                elabel.setText("Bad Email");
            }
            if (x>5 && cemail.getText().substring(x-4,x).equals(".com") && at==true) {
                dotcom=true;
            } else {
                elabel.setForeground(Color.red);
                elabel.setText("Bad Email");
            }
            if (at==true && dotcom==true) {
                elabel.setForeground(Color.blue);
                elabel.setText("Good Email");
            }
        }
    }//GEN-LAST:event_cemailKeyReleased

    private void cbdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbdayActionPerformed

    private void cbdayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbdayKeyReleased

        try {
            int date = cbday.getText().length();
            String mon = cbday.getText().substring(date-10, date-8);
            String day = cbday.getText().substring(date-7, date-5);
            String year = cbday.getText().substring(date-4, date);

            int m=Integer.parseInt(mon);
            int d=Integer.parseInt(day);
            int y=Integer.parseInt(year);

            LocalDate localdate = LocalDate.of(y, m, d);
            LocalDate today = LocalDate.now();

            Period diff = Period.between(localdate, today);

            int age = diff.getYears();

            if (age<18) {
                blabel.setForeground(Color.red);
                blabel.setText("Minors are not allowed.");
            } else {
                blabel.setForeground(Color.blue);
                blabel.setText("Good Format");
            }
        }
        catch (Exception e) {
            blabel.setForeground(Color.red);
            blabel.setText("Wrong Format");
        }
    }//GEN-LAST:event_cbdayKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String birth = blabel.getText();
        String email = elabel.getText();
        Boolean inc = false;
        Boolean badem = false;
        Boolean wb = false;
        Boolean min = false;

        if (cname.getText().length()==0 || cemail.getText().length()==0 || cbday.getText().length()==0 || cad.getText().length()==0 || ccon.getText().length()==0) {
            messagebox ("Incomplete", "Record");
            inc=true; }

        if (email.equals("Bad Email")) {
            messagebox ("Bad Email Format", "Record");
            badem=true; }

        if (birth.equals("Wrong Format")) {
            messagebox ("Wrong Birthday Format", "Record");
            wb=true; }

        int date = cbday.getText().length();
        String mon = cbday.getText().substring(date-10, date-8);
        String day = cbday.getText().substring(date-7, date-5);
        String year = cbday.getText().substring(date-4, date);

        int m=Integer.parseInt(mon);
        int d=Integer.parseInt(day);
        int y=Integer.parseInt(year);

        LocalDate localdate = LocalDate.of(y, m, d);
        LocalDate today = LocalDate.now();

        Period diff = Period.between(localdate, today);

        int age = diff.getYears();

        if (age<18) {
            messagebox ("Minors are not allowed.", "Record");
            min=true; }

        if (inc==false && badem==false && wb==false && min==false) {
            messagebox ("Save!!", "Record");
            
            int x=0;
            try {
                for (int n=1; n<=jTable1.getRowCount(); n++){
                    for (x=0; x<jTable1.getRowCount(); x++) {
                        if (n== Integer.parseInt(jTable1.getModel().getValueAt(x,0).toString())){
                            x+=10;
                        }
                    }
                    if (x ==jTable1.getRowCount()){
                        cid.setText(String.valueOf(n));
                        break;
                    }
                }
                if (x!= jTable1.getRowCount()){
                    String id = String.valueOf(jTable1.getRowCount()+1);
                    cid.setText(id);
                }
            }
            catch (Exception e){
                System.out.println ("Exception:" +e);
            }
                DefaultTableModel tblmodel = (DefaultTableModel) jTable1.getModel();
                String gen = (String)cgen.getSelectedItem();
                String[] item={cid.getText(),cname.getText(),cad.getText(),ccon.getText(),cemail.getText(),cbday.getText(),gen};
                
                tblmodel.addRow(item);
                
                for (int z=0; z<7; z++){ //for the customer array
                cust[Integer.parseInt(cid.getText())-1][z] = item[z];
                
                
            }
            second s = new second();
            s.writecvs(cust);          
        }
    }//GEN-LAST:event_jButton1ActionPerformed
                                          

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int[] selectRow=jTable1.getSelectedRows();
        cid.setText(jTable1.getValueAt(selectRow[0],0).toString());
        cname.setText(jTable1.getValueAt(selectRow[0],1).toString());
        cad.setText(jTable1.getValueAt(selectRow[0],2).toString());
        ccon.setText(jTable1.getValueAt(selectRow[0],3).toString());
        cemail.setText(jTable1.getValueAt(selectRow[0],4).toString());
        cbday.setText(jTable1.getValueAt(selectRow[0],5).toString());
        cgen.setSelectedItem(jTable1.getValueAt(selectRow[0],6).toString());
        
        showorders();
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cid.setEditable(false);
        cid.setText("1");
        
        DefaultTableModel tblmodel = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel tblmodel2 = (DefaultTableModel) jTable3.getModel();
        second s = new second();
        
        for(int x=0; x<s.readcvs().length;x++){    //copy customer cvs to cust array
            if(s.readcvs()[x][0] != null){
                cust[Integer.parseInt(s.readcvs()[x][0])-1] = s.readcvs()[x]; 
                tblmodel.addRow(cust[x]);     //show customers in table
            }
        }
        
        
        for(int x=0;x<s.readcvsord().length;x++){
            for(int y=0;y<s.readcvsord()[x][0].length;y++){
                if(s.readcvsord()[x][y][0] != null){
                    for(int z=0;z<8;z++){
                        ord[x][y][z] = s.readcvsord()[x][y][z];
                        
                    }
                    tblmodel2.addRow(ord[x][y]);
                }
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Products a = new Products();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        for (int z=0; z<7; z++){   //for the customer array
                cust[Integer.parseInt(cid.getText())-1][z] = null;
            }
        
        second s = new second();
        s.writecvs(cust);
        
        DefaultTableModel tblmodel = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRowCount()==1){
            tblmodel.removeRow(jTable1.getSelectedRow());
            
            String value = cid.getText();
            int a = Integer.parseInt(value); 
            System.out.println (a);
            
            for (int n=0; n<num.length; n++){
                if (a == num[n]){
                    num[n] = 0;
                }  
            }
            System.out.println(num);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel tblmodel = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRowCount()==1){
            String gen = (String)cgen.getSelectedItem();
            String[] item={cid.getText(),cname.getText(),cad.getText(),ccon.getText(),cemail.getText(),cbday.getText(),gen};
        
            tblmodel.addRow(item);
            
            tblmodel.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AddOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOrdActionPerformed
        a = Integer.parseInt(cid.getText());
        
        second.ordquan += 1;
        second.trans[0] = String.valueOf(100+a);
        
        for (int x=0; x<10; x++) {
            if (ord[a][x][0]==null) {
                for (int y=0; y<8;y++){
                    ord[a][x][y] = second.trans[y];
                }
                break;
            }
            else if (ord [a][x][7].equals(second.trans[7])){
                ord[a][x][4]=String.valueOf (Integer.parseInt(ord[a][x][4])+1);
                break;
            }
        }
        int y = Integer.parseInt(cid.getText());
        
        DefaultTableModel tblmodel = (DefaultTableModel) jTable3.getModel();
        tblmodel.setRowCount(0);
        
        for (int x=0; x<7;x++) {
            if (ord[y][x][0]!=null){
                tblmodel.addRow(ord[y][x]);
            }
        }
        
        second f = new second();
        f.writecvsord(ord); 
        
    }//GEN-LAST:event_AddOrdActionPerformed

    private void InvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvoiceActionPerformed
        Document doc = new Document();
        PdfWriter docWriter = null;
        second s = new second();
        
        try{
            Font title = new Font(FontFamily.HELVETICA, 20, Font.BOLD, new BaseColor(0,0,0));
            Font bold = new Font(FontFamily.HELVETICA, 12, Font.BOLD, new BaseColor(0,0,0));
            Font notbold = new Font(FontFamily.HELVETICA, 12);
            String path = "C:\\Users\\Licup\\Downloads\\PM Programming\\csvfiles\\finalinvoice.pdf";
            docWriter = PdfWriter.getInstance(doc, new FileOutputStream(path));
            doc.open();
            float[] columnWidths = {25f, 20f, 20f, 25f};
            float[] columnWidths2 = {50f, 20f, 20f};
            PdfPTable table = new PdfPTable(columnWidths);
            PdfPTable table2 = new PdfPTable(columnWidths2);
            
            table.setWidthPercentage(90f);
            table2.setWidthPercentage(90f);
            
            //title
            s.createCell(table,"Computer Programming Store",Element.ALIGN_CENTER,4,title,0,154, 243, 157);
            //space
            s.createCell(table,"",Element.ALIGN_CENTER,4,title,0,255, 255, 255);
            //first row
            s.createCell(table,"Bill To:",Element.ALIGN_LEFT,1,bold,0,188, 250, 190);
            s.createCell(table,"   ",Element.ALIGN_CENTER,2,bold,0,255, 255, 255);
            s.createCell(table,"INVOICE",Element.ALIGN_LEFT,1,bold,0,188, 250, 190);
            
            int i = Integer.parseInt(cid.getText())-1; //ID 
            String[][] array = {{"Customer ID: ","Invoice: ","Date: "},{cid.getText(),String.valueOf(i+101),String.valueOf(LocalDate.now())}};
            //next few rows
            for(int x=0;x<3;x++){
                s.createCell(table,cust[i][x+1],Element.ALIGN_LEFT,1,notbold,0,255, 255, 255);
                s.createCell(table,"   ",Element.ALIGN_CENTER,1,bold,0,255, 255, 255);
                s.createCell(table,array[0][x],Element.ALIGN_RIGHT,1,notbold,0,255, 255, 255);
                s.createCell(table,array[1][x],Element.ALIGN_LEFT,1,notbold,0,188, 250, 190);
            }
            
            //space
            s.createCell(table,"",Element.ALIGN_CENTER,4,title,0,255, 255, 255);
            
            //table 2
            s.createCell(table2,"Product/Description",Element.ALIGN_CENTER,1,bold,1,154, 243, 157);
            s.createCell(table2,"Quantity",Element.ALIGN_CENTER,1,bold,1,154, 243, 157);
            s.createCell(table2,"Unit Price",Element.ALIGN_CENTER,1,bold,1,154, 243, 157);
            //table 2 content
            i += 1;
            int subTotal = 0; 
            for(int x=0;x<ord[i].length;x++){
                if (ord[i][x][0] != null){
                    s.createCell(table2,ord[i][x][2]+" "+ord[i][x][3],Element.ALIGN_LEFT,1,notbold,1,255, 255, 255);
                    s.createCell(table2,ord[i][x][4],Element.ALIGN_CENTER,1,notbold,1,255, 255, 255);
                    s.createCell(table2,ord[i][x][5],Element.ALIGN_CENTER,1,notbold,1,255, 255, 255);
                    subTotal += Integer.parseInt(ord[i][x][4])*Integer.parseInt(ord[i][x][5]);
                    
                }
            }
            
            DecimalFormat numberFormat = new DecimalFormat("#.00");
            //space
            s.createCell(table2,"   ",Element.ALIGN_CENTER,0,bold,0,255, 255, 255);
            s.createCell(table2,"SubTotal",Element.ALIGN_CENTER,1,bold,1,255, 255, 255);
            s.createCell(table2,String.valueOf(numberFormat.format(subTotal)),Element.ALIGN_CENTER,1,bold,1,255, 255, 255);
            s.createCell(table2,"   ",Element.ALIGN_CENTER,1,bold,0,255, 255, 255);
            s.createCell(table2,"Tax 12%",Element.ALIGN_CENTER,1,bold,1,255, 255, 255);
            s.createCell(table2,String.valueOf(numberFormat.format(subTotal*0.12)),Element.ALIGN_CENTER,1,bold,1,255, 255, 255);
            s.createCell(table2,"   ",Element.ALIGN_CENTER,1,bold,0,255, 255, 255);
            s.createCell(table2,"Total",Element.ALIGN_CENTER,1,bold,1,255, 255, 255);
            s.createCell(table2,String.valueOf(numberFormat.format(subTotal*1.12)),Element.ALIGN_CENTER,1,bold,1,255, 255, 255);
            
            Paragraph paragraph = new Paragraph();
            paragraph.add(table);
            paragraph.add(table2);
            doc.add(paragraph);
                    
        }catch(Exception ex){
            System.out.print("Error in pdf creation");}
        
        if(doc != null){
            doc.close();}
        if(docWriter != null){
            docWriter.close();} 
        
        try{
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + "C:\\Users\\Licup\\Downloads\\PM Programming\\csvfiles\\finalinvoice.pdf");
            System.out.println("YAS");
        }catch(Exception ex){
            System.out.print("Error in opening pdf");}
    }//GEN-LAST:event_InvoiceActionPerformed

    private void messagebox(String msg, String titlebar) {
        JOptionPane.showMessageDialog(null, msg, "InfoBox: " + titlebar, JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOrd;
    private javax.swing.JButton Invoice;
    private javax.swing.JLabel blabel;
    private javax.swing.JTextField cad;
    private javax.swing.JTextField cbday;
    private javax.swing.JTextField ccon;
    private javax.swing.JTextField cemail;
    private javax.swing.JComboBox<String> cgen;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cname;
    private javax.swing.JLabel elabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel nlabel;
    // End of variables declaration//GEN-END:variables
}
