/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prog2exer3;

import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author priscillalicup
 */
public class Products extends javax.swing.JFrame {
int a=0;
int b = 0;
String [][] prod1 = new String [10][7];
String [][][] prod2 = new String [10][10][8];

    /**
     * Creates new form Products
     */
    public Products() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Quan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TotCost = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DateRec = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ProdType = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Stock = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ProdId = new javax.swing.JTextField();
        ProdDesc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Supp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        AddQuan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LabCos = new javax.swing.JTextField();
        OvCos = new javax.swing.JTextField();
        DesProf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Product ID");

        Quan.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Product Type");

        TotCost.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Product Description");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Supplier");

        ProdType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdTypeActionPerformed(evt);
            }
        });

        Save.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Save.setText("New Product");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Quantity");

        Stock.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Stock.setText("Stock In");
        Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("Total Cost");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText("Date Received");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("New Products Stock-In");

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PType", "PDesc", "Supplier", "TotQuantity", "Orders"
            }
        ));
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        jLabel2.setText("+");

        AddQuan.setText("0");

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "PType", "PDesc", "Supplier", "Quantity", "Cost", "Date Received", "Orders"
            }
        ));
        Table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table2);

        jLabel7.setText("Labor Cost");

        jLabel11.setText("Overhead Cost");

        jLabel12.setText("Desired Profit");

        LabCos.setText("0");
        LabCos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LabCosKeyReleased(evt);
            }
        });

        OvCos.setText("0");
        OvCos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                OvCosKeyReleased(evt);
            }
        });

        DesProf.setText("0");
        DesProf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DesProfKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Stock))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ProdId, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                        .addComponent(ProdType)
                                        .addComponent(ProdDesc)
                                        .addComponent(Supp)
                                        .addComponent(TotCost)
                                        .addComponent(DateRec, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Quan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AddQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(OvCos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DesProf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabCos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(237, 237, 237))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ProdId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ProdType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ProdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Supp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Quan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(AddQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TotCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(DateRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Save)
                            .addComponent(Stock))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(LabCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(OvCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(DesProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void ProdTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdTypeActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        a = Table1.getRowCount();
        ProdId.setText(String.valueOf(a+1));
        DefaultTableModel tblmodel1 = (DefaultTableModel) Table1.getModel();
        String[] item = {ProdId.getText(), ProdType.getText(), ProdDesc.getText(),Supp.getText(),Quan.getText(),TotCost.getText(),String.valueOf(LocalDate.now()),"0"};
        
        for (int x=0; x<5;x++){
            prod1[a][x] = item[x];
        }
        prod1[a][5]="0";
        tblmodel1.addRow(prod1[a]);
        
        second s = new second();
        prod2 = s.bye(prod2, item, a);
        
        s.writecvsprod(prod1);            
        s.writecvssto(prod2);
    }//GEN-LAST:event_SaveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ProdId.setEditable(false);
        ProdId.setText("1");
        
        second s = new second();
        DefaultTableModel tbl = (DefaultTableModel) Table1.getModel();
       
        for(int x=0; x<s.readcvsprod().length;x++){
            if(s.readcvsprod()[x][0] != null){
                prod1[x] = s.readcvsprod()[x];
                tbl.addRow(prod1[x]);
            }
        }
        
        for(int x=0;x<10;x++){
            for(int y=0;y<10;y++){
                if(s.readcvssto()[x][y][0] != null){
                    for(int z=0;z<8;z++){
                        prod2[x][y][z] = s.readcvssto()[x][y][z];
                    }
                }
            }
        }
        
        second.labcos = Integer.parseInt(s.readcvscost()[0]);
        second.overcos = Integer.parseInt(s.readcvscost()[1]);
        second.desprof = Integer.parseInt(s.readcvscost()[2]);
        
        LabCos.setText(s.readcvscost()[0]);
        OvCos.setText(s.readcvscost()[1]);
        DesProf.setText(s.readcvscost()[2]);
    }//GEN-LAST:event_formWindowOpened

    private void Table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table2MouseClicked
        b = Table2.getSelectedRow();
        
        second.quan = Integer.parseInt(prod2[a][b][4]);
        second.cos = Integer.parseInt(prod2[a][b][5]);
        second.index = a*10+b;
        
        second s = new second();
        s.hello(prod2[a][b]);
        
    }//GEN-LAST:event_Table2MouseClicked

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        int [] selectRow = Table1.getSelectedRows();
        ProdId.setText(Table1.getValueAt(selectRow[0],0).toString());
        ProdType.setText(Table1.getValueAt(selectRow[0],1).toString());
        ProdDesc.setText(Table1.getValueAt(selectRow[0],2).toString());
        Supp.setText(Table1.getValueAt(selectRow[0],3).toString());
        Quan.setText(Table1.getValueAt(selectRow[0],4).toString());
        AddQuan.setText("");
        TotCost.setText("");
        
        prod2[a][b][4] = String.valueOf(Integer.parseInt(prod2[a][b][4])-second.ordquan);
        prod2[a][b][7] = String.valueOf(Integer.parseInt(prod2[a][b][7])+second.ordquan);
        System.out.println (prod1 [a][5]);
        //prod1 [a][5] = String.valueOf(prod1 [a][5] + second.ordquan);
        
        prod1[a][5] = String.valueOf(Integer.parseInt(prod1[a][5])+second.ordquan);
        System.out.println (prod1 [a][5]);
        
        
        /* DefaultTableModel tbl = (DefaultTableModel) Table1.getModel();
        a = Table1.getSelectedRow();
        tbl.setValueAt (ProdId.getText(),a,0);
        tbl.setValueAt (ProdType.getText(),a,1);
        tbl.setValueAt (ProdDesc.getText(),a,2);
        tbl.setValueAt (Supp.getText(),a,3);
        tbl.setValueAt (Quan.getText(),a,4);
        tbl.setValueAt (prod1 [a][5],a,5); */
        
        
        
        second.ordquan = 0;
        
        a = Table1.getSelectedRow();
        DefaultTableModel tblmodel2 = (DefaultTableModel) Table2.getModel();
        tblmodel2.setRowCount(0);
        for (int x=0; x<10;x++){
            if (prod2[a][x][0]!=null){
                tblmodel2.addRow(prod2[a][x]);
            }
        }
        DefaultTableModel tbl = (DefaultTableModel) Table1.getModel();
        a = Table1.getSelectedRow();
        tbl.setValueAt (prod1[a][5],a,5);
        
        /*DefaultTableModel tbl = (DefaultTableModel) Table1.getModel();
        a = Table1.getSelectedRow();
        tbl.setRowCount(0);
        for (int x=0; x<10;x++){
            if (prod1[a][x]!=null){
                tbl.addRow(prod2[a]);
            }
        } */
        
        second s = new second();
        s.writecvsprod(prod1);
        s.writecvssto(prod2);
                 
    }//GEN-LAST:event_Table1MouseClicked

    private void StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockActionPerformed
        a = Integer.parseInt (ProdId.getText())-1;
        
        String[] item = {ProdId.getText(), ProdType.getText(), ProdDesc.getText(),Supp.getText(),AddQuan.getText(),TotCost.getText(),String.valueOf(LocalDate.now()),"0"};
        
        second s = new second();
        prod2=s.bye(prod2,item,a);
        
        prod1[a][4]=String.valueOf(Integer.parseInt(prod1[a][4])+Integer.parseInt(AddQuan.getText()));
        DefaultTableModel tblmodel1 = (DefaultTableModel) Table1.getModel();
        tblmodel1.setValueAt(prod1[a][4],a,4);
        Quan.setText(Table1.getValueAt(a,4).toString());

        DefaultTableModel tblmodel2 = (DefaultTableModel) Table2.getModel();
        tblmodel2.setRowCount(0);
        for (int x=0; x<10;x++){
            if (prod2[a][x][0]!=null){
                tblmodel2.addRow(prod2[a][x]);
            }
        }
       s.writecvssto(prod2); 
    }//GEN-LAST:event_StockActionPerformed

    private void LabCosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LabCosKeyReleased
        second s = new second();
        
        if (LabCos.getText().length()>0){
            second.labcos = Integer.parseInt(LabCos.getText());
            s.writecvscost();
        }
    }//GEN-LAST:event_LabCosKeyReleased

    private void OvCosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OvCosKeyReleased
        second s = new second();
        
        if (OvCos.getText().length()>0){
            second.overcos = Integer.parseInt(OvCos.getText());
            s.writecvscost();
        }
    }//GEN-LAST:event_OvCosKeyReleased

    private void DesProfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DesProfKeyReleased
        second s = new second();
        
        if (DesProf.getText().length()>0){
            second.desprof = Integer.parseInt(DesProf.getText());
            s.writecvscost();
        }
    }//GEN-LAST:event_DesProfKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddQuan;
    private javax.swing.JTextField DateRec;
    private javax.swing.JTextField DesProf;
    private javax.swing.JTextField LabCos;
    private javax.swing.JTextField OvCos;
    private javax.swing.JTextField ProdDesc;
    private javax.swing.JTextField ProdId;
    private javax.swing.JTextField ProdType;
    private javax.swing.JTextField Quan;
    private javax.swing.JButton Save;
    private javax.swing.JButton Stock;
    private javax.swing.JTextField Supp;
    private javax.swing.JTable Table1;
    private javax.swing.JTable Table2;
    private javax.swing.JTextField TotCost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
